name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Maven with Xvfb
      uses: run-with-xvfb
      with:
        run: mvn -B package --file pom.xml
      env:
        CI: true
