name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Maven with Xvfb
      run: sudo apt-get install xvfb
      run: export DISPLAY=':99.0'
      run: export AUDIODEV=null
      run: xvfb-run :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      run: mvn -B package --file pom.xml
